name: doctor_appointment
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publication

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  sliding_clipped_nav_bar: ^3.1.1
  easy_date_timeline: ^1.1.3
  cloud_firestore: ^5.2.1
  shared_preferences: ^2.3.1
  image_cropper: ^8.0.1
  image_picker: ^1.1.2

  uuid: ^4.4.2
  firebase_storage: ^12.1.3
  path_provider: ^2.0.10
  dio: ^5.0.3
#  chewie: ^1.7.5
  permission_handler: ^11.3.1
  flutter_rating_bar: ^4.0.1

#  video_player: any
  uid: ^0.0.2
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/home_screen_image/
    - assets/home_screen_image/doctor-images/

